apiVersion: v1
kind: ConfigMap
metadata:
  name: ethereum2-script-prysm-mainnet-v2
  namespace: blockchain
data:
  sync-status.sh: |
    #!/bin/bash
    curl -s -X GET "http://localhost:13502/eth/v1alpha1/node/syncing" -H "accept: application/json" -o eth2-mainnet-sync-status.txt
    export ETH2_SYNC=$(jq -r ".syncing" eth2-mainnet-sync-status.txt)
    export VAR2=false
    rm -f eth2-mainnet-sync-status.txt

    if [ $ETH2_SYNC = $VAR2 ]
        then
         echo "ETH2 node is in sync"
         exit 0
    else
         echo "ETH2 node not in sync" >&2
         exit 1
    fi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ethereum2-script-prysm-mainnet-grpc-v2
  namespace: blockchain
data:
  grpc-status.sh: |
    #!/bin/bash
    export GRPC_STATUS=$(grpcurl -max-time 3 -plaintext -H "x-user: ricky" localhost:14002 list  |grep ethereum.beacon.rpc.v1.Health)
    export GRPC_VAR1=ethereum.beacon.rpc.v1.Health

    if [ $GRPC_STATUS = $GRPC_VAR1 ]
        then
         echo "ETH2 grpc is ok"
         exit 0
    else
         echo "ETH2 grpc it not ok" >&2
         exit 1
    fi
